// PM2 ecosystem config — runs all FloyDex background services.
// Usage: pm2 start ecosystem.config.cjs
//        pm2 stop all
//        pm2 logs
//        pm2 monit

module.exports = {
  apps: [
    {
      name: "floydex-oracle",
      script: "npx",
      args: "tsx --env-file=../.env scripts/oracle-keeper.ts",
      cwd: __dirname,
      restart_delay: 5000,
      max_restarts: 20,
      autorestart: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "./logs/oracle.log",
      error_file: "./logs/oracle.error.log",
    },
    {
      name: "floydex-matcher",
      script: "npx",
      args: "tsx --env-file=../.env scripts/matcher-service.ts",
      cwd: __dirname,
      restart_delay: 3000,
      max_restarts: 20,
      autorestart: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "./logs/matcher.log",
      error_file: "./logs/matcher.error.log",
    },
    {
      name: "floydex-indexer",
      script: "npx",
      args: "tsx --env-file=../.env scripts/state-indexer.ts",
      cwd: __dirname,
      restart_delay: 5000,
      max_restarts: 20,
      autorestart: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "./logs/indexer.log",
      error_file: "./logs/indexer.error.log",
    },
    {
      name: "floydex-ws",
      script: "npx",
      args: "tsx --env-file=../.env scripts/ws-server.ts",
      cwd: __dirname,
      env: { PORT: "8080" },
      restart_delay: 3000,
      max_restarts: 20,
      autorestart: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "./logs/ws.log",
      error_file: "./logs/ws.error.log",
    },
    {
      name: "floydex-liquidator",
      script: "npx",
      args: "tsx --env-file=../.env scripts/liquidation-keeper.ts",
      cwd: __dirname,
      restart_delay: 5000,
      max_restarts: 20,
      autorestart: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "./logs/liquidator.log",
      error_file: "./logs/liquidator.error.log",
    },
    {
      name: "floydex-reconciler",
      script: "npx",
      args: "tsx --env-file=../.env scripts/settlement-reconciler.ts",
      cwd: __dirname,
      restart_delay: 10000,
      max_restarts: 10,
      autorestart: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "./logs/reconciler.log",
      error_file: "./logs/reconciler.error.log",
    },
    {
      name: "floydex-monitor",
      script: "npx",
      args: "tsx --env-file=../.env scripts/monitor.ts",
      cwd: __dirname,
      // The local WS server, not the public NEXT_PUBLIC_WS_URL from ../.env.
      env: { MONITOR_WS_URL: "ws://localhost:8080" },
      restart_delay: 10000,
      max_restarts: 20,
      autorestart: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "./logs/monitor.log",
      error_file: "./logs/monitor.error.log",
    },
  ],
};
